version: 2
updates:
  - package-ecosystem: "npm"
    directory: "../website"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "../app/python-factory-web-search"
    schedule:
      interval: "daily"
