version: 2
updates:
  - package-ecosystem: "npm"
    directory: "../app/Python-Factory"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "../vue/nuxt"
    schedule:
      interval: "daily"
